version: '2'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - env/app
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: postgres:10.4
    env_file:
      - env/db
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/db:/var/lib/postgresql/data