"""Added init table

Revision ID: c125513ec835
Revises: 
Create Date: 2023-01-06 05:09:30.277990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c125513ec835'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_api_parsingsession',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('twitter_api_parsingsessionaccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('twitter_id', sa.String(length=56), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='{pending}', nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['twitter_api_parsingsession.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_api_parsingsessionaccount_session_id'), 'twitter_api_parsingsessionaccount', ['session_id'], unique=False)
    op.create_index(op.f('ix_twitter_api_parsingsessionaccount_status'), 'twitter_api_parsingsessionaccount', ['status'], unique=False)
    op.create_index(op.f('ix_twitter_api_parsingsessionaccount_twitter_id'), 'twitter_api_parsingsessionaccount', ['twitter_id'], unique=False)
    op.create_table('twitter_api_tweet',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parsing_session_account_id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.String(length=56), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parsing_session_account_id'], ['twitter_api_parsingsessionaccount.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twitter_api_tweet_parsing_session_account_id'), 'twitter_api_tweet', ['parsing_session_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_twitter_api_tweet_parsing_session_account_id'), table_name='twitter_api_tweet')
    op.drop_table('twitter_api_tweet')
    op.drop_index(op.f('ix_twitter_api_parsingsessionaccount_twitter_id'), table_name='twitter_api_parsingsessionaccount')
    op.drop_index(op.f('ix_twitter_api_parsingsessionaccount_status'), table_name='twitter_api_parsingsessionaccount')
    op.drop_index(op.f('ix_twitter_api_parsingsessionaccount_session_id'), table_name='twitter_api_parsingsessionaccount')
    op.drop_table('twitter_api_parsingsessionaccount')
    op.drop_table('twitter_api_parsingsession')
    # ### end Alembic commands ###
